services:
  ceramic:
    image: public.ecr.aws/r5b3e0r5/3box/ceramic-one:0.53.0
    container_name: ceramic-one
    restart: on-failure
    ports:
      - 4101:4101 # swarm TCP
      - 4102:4102 # swarm UDP
      - 5101:5101 # RPC
      - 5102:5102 # flight SQL (> v0.53.0)
      - 9465:9465 # prometheus metrics
    environment:
      CERAMIC_ONE_STORE_DIR: "/data/ceramic-one"
      CERAMIC_ONE_P2P_KEY_DIR: "/data/ceramic-one"
      CERAMIC_ONE_BIND_ADDRESS: "0.0.0.0:5101"
      CERAMIC_ONE_SWARM_ADDRESSES: "/ip4/0.0.0.0/tcp/4101,/ip4/0.0.0.0/udp/4102/quic-v1"
      CERAMIC_ONE_METRICS_BIND_ADDRESS: "0.0.0.0:9465"
      CERAMIC_ONE_FLIGHT_SQL_BIND_ADDRESS: "0.0.0.0:5102"
      CERAMIC_ONE_LOCAL_NETWORK_ID: "0"
      CERAMIC_ONE_NETWORK: "testnet-clay"
      RUST_LOG: "info,recon::protocol=debug,ceramic_one=debug,multipart=error"
      # CERAMIC_ONE_LOG_FORMAT: "json"
    env_file:
      packages/models/.env
    volumes:
      - ./local-data/ceramic-one:/data/ceramic-one
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail-with-body",
          "http://localhost:5101/ceramic/liveness",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
  
