on:
  push:
    paths:
      - .github/workflows/build-node.yml
      - packages/node/**
      - packages/lib/**
      - packages/models/**
    branches:
      - main

env:
  AWS_DEFAULT_REGION: us-east-2
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS and Kubernetes
        uses: ./.github/actions/setup-aws-k8s
        with:
          kube-config-data: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Build and push codex-node image
        uses: ./.github/actions/docker-build-push
        with:
          image-name: codex-node
          dockerfile-path: packages/node/Dockerfile
          build-context: .

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS and Kubernetes
        uses: ./.github/actions/setup-aws-k8s
        with:
          kube-config-data: ${{ secrets.KUBE_CONFIG_DATA }}

      - name: Deploy codex-node to EKS
        uses: ./.github/actions/k8s-deploy
        with:
          manifest-path: packages/node/k8s/dev/deployment.yaml
          deployment-type: statefulset
          deployment-name: codex-node-dev
          container-name: codex-node
          image-name: codex-node