name: Publish codex-lib to npmjs
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
          check-latest: false
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install
      - run: |
          pnpm --filter @desci-labs/desci-codex-lib doPublish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
